package model;


public class Ocean {
	private int width;
	private int depth;
	private Fish fish;

	public Ocean(int width, int depth, Fish fish) {
		this.width = width;
		this.depth = depth;
		this.fish = fish;
	}

	public void move() {
		// TODO do sth with x and y of fish
	}

	public String toString() {
		return "Width: " + this.width + ", Depth: " + this.depth + ", " + fish;
	}

	// Autogenerated getters and setters

	public int getWidth() {
		return width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	public int getDepth() {
		return depth;
	}

	public void setDepth(int depth) {
		this.depth = depth;
	}

	public Fish getFish() {
		return fish;
	}

	public void setFish(Fish fish) {
		this.fish = fish;
	}

}
