package model;

import java.util.Random;

public class Ocean {
	private int width;
	private int depth;
	private Fish fish;

	public Ocean(int width, int depth, Fish fish) {
		this.width = width;
		this.depth = depth;
		this.fish = fish;
	}

	public void move() {
		// get fish position
		int xPos = fish.getX();
		int yPos = fish.getY();
		// randomize delta to move fish
		Random rand = new Random();
		int xMove = rand.nextInt(61) - 30;
		int yMove = rand.nextInt(61) - 30;
		// if new location is valid, move fish accordingly
		if ((xPos + xMove >= 0) && (xPos + xMove <= width)) {
			fish.setX(xPos + xMove);
		}
		if ((yPos + yMove >= 0) && (yPos + yMove <= depth)) {
			fish.setY(yPos + yMove);
		}

	}

	public String toString() {
		return "Width: " + this.width + ", Depth: " + this.depth + ", " + fish;
	}

	// Autogenerated getters and setters

	public int getWidth() {
		return width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	public int getDepth() {
		return depth;
	}

	public void setDepth(int depth) {
		this.depth = depth;
	}

	public Fish getFish() {
		return fish;
	}

	public void setFish(Fish fish) {
		this.fish = fish;
	}

}
